# Generated by Django 4.0 on 2021-12-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chatid',
            field=models.IntegerField(unique=True),
        ),
    ]
